services:
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "./.redis_data:/data"

  web:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
    volumes:
      - ".:/code"
    entrypoint:
      - /bin/sh
      - "-c"
      - |
        gunicorn backtick.views:app --workers 4 \
          --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
    volumes:
      - ".:/code"
    environment:
      - PYTHONPATH=/code
    entrypoint: python -m backtick.worker --with-scheduler
    depends_on:
      - web
      - redis
