
FROM python:3.11-slim-bullseye

# Set environment variables.
ENV PYTHONWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

# Set working directory.
WORKDIR /code

# Copy dependencies.
COPY requirements.txt requirements-dev.txt /code/

# Install dependencies.
RUN pip install -r requirements.txt -r requirements-dev.txt

# Copy project.
COPY . /code/

EXPOSE 5000
